name: Windows Test

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "GitHub Actions on Windows!"
